 /*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

 import org.example.application.usecases.*;
 import org.example.application.usecases.models.responses.GetBoardResult;
 import org.example.application.usecases.models.responses.GetTaskResult;
 import org.example.domain.model.BoardRepository;
 import org.example.domain.model.TaskRepository;
 import org.example.infrastructure.cli.BoardMenuHandler;
 import org.example.infrastructure.cli.MainMenuHandler;
 import org.example.infrastructure.cli.TaskMenuHandler;
 import org.example.infrastructure.handlers.board.CreateBoardCommandHandler;
 import org.example.infrastructure.handlers.board.GetAvailableBoardsHandler;
 import org.example.infrastructure.handlers.task.CreateTaskCommandHandler;
 import org.example.infrastructure.handlers.task.GetTaskListCommandHandler;
 import org.example.infrastructure.persistence.JsonBoardRepository;
 import org.example.infrastructure.persistence.JsonTaskRepository;
 import org.example.infrastructure.persistence.jsonconfig.DataConfig;

 import java.util.Scanner;
 import java.util.logging.Logger;

 public class App {

    public static void main(String[] args) {
        start();
    }

     public static void start() {
         Scanner scanner = new Scanner(System.in);

         // Setup all dependencies in App (Composition Root)
         MainMenuHandler mainMenu = setupDependencies(scanner);

         // Start application
         mainMenu.showMenu();
     }

     private static MainMenuHandler setupDependencies(Scanner scanner) {

         Logger logger = Logger.getLogger(App.class.getName());
         GetTaskResult getTaskResultBuilder = new GetTaskResult(logger);
         GetBoardResult getBoardResultBuilder = new GetBoardResult(logger);


         // 1. Setup Repositories
         TaskRepository taskRepository = new JsonTaskRepository(DataConfig.getTasksFilePath());
         BoardRepository boardRepository = new JsonBoardRepository(DataConfig.getBoardsFilePath());

         // 2. Setup Use Cases
         CreateTaskUseCase createTaskUseCase = new CreateTaskUseCaseImpl(taskRepository);
         GetBoardsUseCase getBoardsUseCase = new GetAvailableBoardsUseCaseImpl(boardRepository,getBoardResultBuilder);
         CreateBoardUseCase createBoardUseCase = new CreateBoardUseCaseImpl(boardRepository);
         GetTasksUseCase getTasksUseCase = new GetTasksUseCaseImpl(taskRepository,getTaskResultBuilder);

         // 3. Setup Command Handlers
         CreateTaskCommandHandler createTaskHandler = new CreateTaskCommandHandler(
                 scanner, createTaskUseCase, getBoardsUseCase);
         CreateBoardCommandHandler createBoardHandler = new CreateBoardCommandHandler(
                 scanner, createBoardUseCase);
         GetAvailableBoardsHandler getBoardHandler = new GetAvailableBoardsHandler(scanner, getBoardsUseCase);
         GetTaskListCommandHandler getTaskListCommandHandler = new GetTaskListCommandHandler(scanner,getTasksUseCase);

         // 4. Setup Menu Handlers
         TaskMenuHandler taskMenuHandler = new TaskMenuHandler(scanner, createTaskHandler,getTaskListCommandHandler);
         BoardMenuHandler boardMenuHandler = new BoardMenuHandler(scanner, createBoardHandler, getBoardHandler);

         // 5. Setup Main Menu
         return new MainMenuHandler(scanner, taskMenuHandler, boardMenuHandler);
     }
}
