 /*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

 import org.example.cli.Router;

 public class App {

    public static void main(String[] args) {
        Router router = new Router();
        router.StartListening();
    }
}
